### ISSUE TITLE
Support for Android reader?

### ISSUE THREAD

**Issue by garrison** [jparyani/Tiny-Tiny-RSS#9]
Would it be possible to support syncing with the Android TTRSS interface (https://github.com/nilsbraden/ttrss-reader-fork)?

I tried entering a "shared" Sandstorm URL of my TTRSS instance into the Android app, but the app complains:

> Error
> 
> I was unable to connect to your Tiny Tiny RSS instance, please check your connection and/or/ connection settings.
> 
> Error details:
> 
> Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

**Comment by ocdtrekkie** [comment]
Are you using the forked version of TTRSS included in the Sandstorm app? Unfortunately attempts to get Sandstorm support in the upstream app were unsuccessful.

**Comment by garrison** [comment]
I am using oasis.sandstorm.io, so yes.

**Comment by ocdtrekkie** [comment]
I mean the forked version of the Android app, sorry.

When you are in TTRSS on Sandstorm, go to Actions (on the top right), then Preferences, and select the Mobile App tab. It will offer a link to download this Android app: https://github.com/jparyani/Tiny-Tiny-RSS-for-Honeycomb

The extent of the changes to support Sandstorm are here: https://github.com/jparyani/Tiny-Tiny-RSS-for-Honeycomb/commit/2beebe832337642f4d24a8d6e84f90f3e57f9e39 so if you'd like to get another TTRSS client to support Sandstorm, it's allegedly fairly simple.

**Comment by garrison** [comment]
> When you are in TTRSS on Sandstorm, go to Actions (on the top right), then Preferences, and select the Mobile App tab. It will offer a link to download this Android app: https://github.com/jparyani/Tiny-Tiny-RSS-for-Honeycomb

I click on the link to download this "apk" from within sandstorm, but nothing happens.  I've tried both on my phone and in chromium, with both the standard oasis URL and the "shared" URL. Is there another place to download the apk?

**Comment by ocdtrekkie** [comment]
Interesting. I'm wondering if the last version of the app might be missing the file. It's not in the sandstorm files list for this package. I suspect it got left behind here: https://github.com/jparyani/Tiny-Tiny-RSS/commit/13f400ee7ce9955e47484ad61547311ade550f88

I can try to email you the APK I have on file.

**Comment by ocdtrekkie** [comment]
Let's do the Sandstormy way of sharing the file!

https://oasis.sandstorm.io/shared/bGgDrzmvdbUGQqGnKdL2W2A9CdOUyfW3mnauPOu2Yn6

**Comment by garrison** [comment]
Thanks for the link.  I managed to get it working, but it still required some persistence.  In the instructions (under the Mobile App tab), the first step is to install the apk and the third step says "Open the TinyTinyRss android app, and in its settings, paste the webkey URL you got from the previous step into the URL field."  But when I view in chromium, the second step (bullet) says nothing -- it is simply a horizontal scroll area for me.  I later managed to get that frame to load in the web browser on my android device, and then it was a bit frustrating trying to select that entire large URL and get it into the app.  But it worked in the end.  Thanks!

I think the overall visibility of the "Mobile App" tab could be improved.  I would have never expected to need to look in preferences in order to find a client that would work with sandstorm.  I had looked in README.md for advice; it may make sense to put a note there, though I expect many users would not even think to look there.

**Comment by garrison** [comment]
Also, the very first thing I tried was to use the [TTRSS app provided via fdroid](https://f-droid.org/repository/browse/?fdid=org.ttrssreader).  It would be great to get sandstorm support working in that version, ideally such that I could simply paste a "shared" oasis URL like I had originally tried.

**Comment by ocdtrekkie** [comment]
TinyTinyRSS on Sandstorm hasn't been updated in a while, the Sandstorm platform is actually a little more capable than it was last time it was updated. I spoke with jparyani, the port's maintainer, on IRC, because Sandstorm is now capable of supporting the same authentication TTRSS supports by default. Note that that will require you copy a URL, a username, and a password, I believe, but it's supported by TTRSS, rather than the modified version required to use bearer tokens.

```
14:59:48 <ocdtrekkie> jparyani: I think the vagrant-spk conversion of TinyTinyRSS may have accidentally dropped the APK file? Also, worthy question, should TTRSS support the new basic auth capability, so that TTRSS clients don't need to be forked?
15:11:34 <jparyani> Ah dang, that's probably right. As to basic auth, ya it should change to showing an offer template and basic auth should work I think. I'll test it out tomorrow.
15:16:58 <asheesh> egad, what a crazy world, no need to fork tt-rss anymore
```

**Comment by alec** [comment]
I figured out how to use HTTP Auth with the upstream Android app and have a [pull request](https://github.com/jparyani/Tiny-Tiny-RSS/pull/11) open to update the documentation.

**Comment by jparyani** [comment]
Fixed by #11.

**Comment by ocdtrekkie** [comment]
As an interesting note for @alec and @garrison: The F-Droid app for TTRSS has allegedly fixed the issue as per https://github.com/nilsbraden/ttrss-reader-fork/issues/317 so when the next release (isn't one yet) hits F-Droid, we should test it again.

**Comment by garrison** [comment]
Looks like a new release (1.91.1) has hit F-Droid.

**Comment by garrison** [comment]
> Looks like a new release (1.91.1) has hit F-Droid.

I'm still unable to get it to work though, following the usual instructions under "Mobile App Setup".
